### PR TITLE
Gecoder in ES6, scale control, some fixes.

### LINKED ISSUE #29: Map Scale is missing
This is something that we forgot to add to the map. I'd suggest placing it to the right of satellite view switcher instead of stacking it upwards!

### PR DESCRIPTION
**Pull request by benjamintd**
- Fix ImageWithFallback that broke with updating react
- Add some tests (slowly)
- Add scale control (fixes #29 )

### CODE REVIEW

File: src/components/StyleSwitch.js [hunk 1]
```diff
@@ -67,6 +67,8 @@ const mapDispatchToProps = (dispatch) => {
   };
 };
 
+export {StyleSwitch};
```
Comment (SrihariThalla) [inline src/components/StyleSwitch.js]: What is the difference between this export and the other on the next line?

File: src/components/Geocoder.js [hunk 2]
```diff
@@ -9,44 +9,27 @@ import xhr from 'xhr';
  * Geocoder component: connects to Mapbox.com Geocoding API
  * and provides an autocompleting interface for finding locations.
  */
-var Geocoder = React.createClass({
```
Comment (SrihariThalla) [inline src/components/Geocoder.js]: Finally! It's good to move to `Component` ;)

File: src/components/StyleSwitch.js (hunk 1 above)
Comment (benjamintd) [inline src/components/StyleSwitch.js]: This is a named export, that allows to use the component unconnected to the store.

That way you can test your component without having to mount it to a Redux store. See [here](http://redux.js.org/docs/recipes/WritingTests.html#connected-components) for more details.
